image: titandino/darkan-runner:v1

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

.cache_gradle:
  cache:
    key: "$CI_COMMIT_REF_NAME-gradle"
    policy: pull-push
    paths:
      - .gradle/caches/
      - .gradle/wrapper/

build:
  stage: build
  script: ./gradlew assemble --build-cache --parallel --max-workers=$(nproc)
  cache:
    key: "$CI_COMMIT_REF_NAME-gradle"
    policy: pull-push
    paths:
      - build/
  artifacts:
    paths:
      - build/
    expire_in: 1 hour
  extends:
    - .cache_gradle

deploy:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "master"'
  script:
    - echo "Deploying build artifacts..."
    - ./gradlew publish --parallel --max-workers=$(nproc)
  environment: production
  dependencies:
    - build
  extends:
    - .cache_gradle