version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: no auth
#      MONGO_INITDB_ROOT_PASSWORD: no auth

  darkan-world-server:
    image: registry.gitlab.com/darkanrs/world-server/world-server:latest
    container_name: darkan-world-server
    ports:
      - "43595:43595"
      - "43596:43596"
    volumes:
      - ./world-data:/darkan/world-server/data
      - ./plugins:/darkan/world-server/plugins
      - ./cache:/darkan/cache
    depends_on:
      - mongodb
#    environment:
#      DARKAN_JAVA_VM_ARGS: -Xms1024 -Xmx4096
